---
version: 2
jobs:
  build:
    docker:
      - image: circleci/rust:1.33

    steps:
      - checkout
      - restore_cache:
          keys:
            - cpu-engine-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Install Cippy
          command: rustup component add clippy
      - run:
          name: Check
          command: cargo check
      - save_cache:
          key: cpu-engine-{{ arch }}-{{ checksum "Cargo.lock" }}
          paths:
            - target/
      - run:
          name: Clippy
          command: cargo clippy --all-targets --all-features -- -D warnings
      - run:
          name: Tests
          command: cargo test
      - run:
          name: Build
          command: cargo build --release
